language: scala

scala:
    - 2.11.7

jdk:
    - oraclejdk7

sudo: false

branches:
    only:
        - master

notifications:
    email:
        - leon-dev@googlegroups.com

before_script:
    - sbt compile
    - sbt script
    - source travis/fetchCVC4.sh

env:
    matrix:
        - TEST_COMMAND="test"
        - TEST_COMMAND="integration:test"
        - TEST_COMMAND="regression:test"

script:
    - sbt ++$TRAVIS_SCALA_VERSION "$TEST_COMMAND"

    # Tricks to avoid unnecessary cache updates
    - find $HOME/.sbt -name "*.lock" | xargs rm
    - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

cache:
    directories:
        - $HOME/.ivy2/cache
        - $HOME/.sbt/boot/
